/**
 * Do not edit directly, this file was auto-generated.
 *
 * BILD Design System Tokens v1.0.0
 * Generated by Style Dictionary v5.1.4
 *
 * Brand: Bild | Context: SemanticColors Light
 *
 * Copyright (c) 2026 Axel Springer Deutschland GmbH
 * Proprietary and confidential. All rights reserved.
 *
 * Documentation: https://github.com/UXWizard25/bild-design-system/blob/main/packages/tokens/docs/android.md
 */
package com.bild.designsystem.brands.bild.semantic.color

import androidx.compose.runtime.Immutable
import androidx.compose.runtime.Stable
import androidx.compose.ui.graphics.Color
import com.bild.designsystem.shared.DesignColorScheme

/**
 * Color scheme interface for Bild
 * Extends DesignColorScheme for Dual-Axis theming compatibility
 * Allows type-safe access to colors and enables color scheme sharing across brands
 *
 * All color properties are inherited from DesignColorScheme.
 * This interface exists to enable brand-specific type checking.
 */
@Stable
interface BildColorScheme : DesignColorScheme

/**
 * Bild Color Scheme - Light Mode
 */
@Immutable
object BildLightColors : BildColorScheme {
    override val textColorBrand = Color(0xFFDD0000)
    override val textColorBrandLightOnly = Color(0xFFDD0000)
    override val textColorPrimary = Color(0xFF222628)
    override val textColorSecondary = Color(0xFF565A5F)
    override val textColorTertiary = Color(0xFF6E787C)
    override val kickerTextColor = Color(0xFFDD0000)
    override val headlineTextColor = Color(0xFF222628)
    override val textColorOnImage = Color(0xFFFFFFFF)
    override val textColorSecondaryOnDark = Color(0xFFDDE1E2)
    override val textColorPrimaryOnLight = Color(0xFF222628)
    override val kickerTextColorOnDark = Color(0xCCFFFFFF)
    override val kickerTextColorOnLight = Color(0xB3000000)
    override val textColorPrimaryOnDark = Color(0xFFFFFFFF)
    override val textColorSecondaryOnLight = Color(0xFF565A5F)
    override val textColorIdle = Color(0xFF565A5F)
    override val textColorDisabled = Color(0xFFA6ABB0)
    override val textColorHover = Color(0xFF222628)
    override val textColorActive = Color(0xFF222628)
    override val textColorPrimaryInverse = Color(0xFFDDE1E2)
    override val textColorSecondaryInverse = Color(0xFFA6ABB0)
    override val textColorInverseHighContrast = Color(0xFFFFFFFF)
    override val textColorSuccess = Color(0xFF006E3E)
    override val textColorError = Color(0xFFC10000)
    override val textColorWarning = Color(0xFF9E4401)
    override val bgColorPrimary = Color(0xFFFFFFFF)
    override val bgColorDisabled = Color(0xFFF2F4F5)
    override val bgColorSecondary = Color(0xFFF2F4F5)
    override val bgColorPrimaryConstDark = Color(0xFF222628)
    override val bgColorQuaternary = Color(0xFFC4C9CF)
    override val bgColorTertiary = Color(0xFFDDE1E2)
    override val bgColorPrimaryConstLight = Color(0xFFFFFFFF)
    override val bgColorQuintenary = Color(0xFF8C9196)
    override val bgColorBrandLightOnly = Color(0xFFDD0000)
    override val bgColorBrandSolid = Color(0xFFDD0000)
    override val bgColorBrandSolidHover = Color(0xFFC10000)
    override val bgColorBrandSolidActive = Color(0xFF930000)
    override val bgColorBrandTint = Color(0xFFFFDADA)
    override val bgColorBrandTintHover = Color(0xFFFFB2B2)
    override val bgColorPrimaryInverse = Color(0xFF222628)
    override val bgColorTertiaryInverse = Color(0xFF343C41)
    override val bgColorQuaternaryInverse = Color(0xFF40464D)
    override val bgColorSecondaryInverse = Color(0xFF2C3133)
    override val bgColorQuintenaryInverse = Color(0xFF8C9196)
    override val bgColorSuccessTint = Color(0xFFDEF7E6)
    override val bgColorSuccessSolid = Color(0xFF158751)
    override val bgColorSuccessSolidHover = Color(0xFF006E3E)
    override val bgColorSuccessTintHover = Color(0xFFB9EFCD)
    override val bgColorSuccessSolidActive = Color(0xFF0D5232)
    override val bgColorTertiaryGradientStop = Color(0x00DDE1E2)
    override val bgColorPrimaryGradientStop = Color(0x00FFFFFF)
    override val bgColorSecondaryGradientStop = Color(0x00F2F4F5)
    override val overlayScrimBlackConst = Color(0xB3000000)
    override val overlayScrimWhiteConst = Color(0xB3FFFFFF)
    override val bgColorErrorTint = Color(0xFFFFECEC)
    override val bgColorErrorTintHover = Color(0xFFFFDADA)
    override val bgColorErrorSolid = Color(0xFFC10000)
    override val bgColorErrorSolidHover = Color(0xFF930000)
    override val bgColorWarningTint = Color(0xFFFFEDDF)
    override val bgColorWarningTintHover = Color(0xFFFEDBC1)
    override val bgColorWarningSolid = Color(0xFFFD8227)
    override val bgColorWarningSolidHover = Color(0xFFEF6702)
    override val borderColorDefault = Color(0xFFC4C9CF)
    override val borderColorSubtle = Color(0xFFDDE1E2)
    override val borderColorExtraStrong = Color(0xFF222628)
    override val borderColorStrong = Color(0xFF6E787C)
    override val borderColorSubtleOnDark = Color(0xFF343C41)
    override val borderColorDefaultOnDark = Color(0xFF565A5F)
    override val borderColorSubtleOnLight = Color(0xFFDDE1E2)
    override val borderColorDefaultOnLight = Color(0xFFC4C9CF)
    override val borderColorSuccess = Color(0xFF006E3E)
    override val borderColorError = Color(0xFFDD0000)
    override val borderColorWarning = Color(0xFFC65502)
    override val borderColorDisabled = Color(0xFFDDE1E2)
    override val borderColorSelected = Color(0xFF40464D)
    override val borderColorActive = Color(0xFFDD0000)
    override val borderColorIdle = Color(0xFF8C9196)
    override val borderColorDefaultInverse = Color(0xFF565A5F)
    override val borderColorSubtleInverse = Color(0xFF343C41)
    override val borderColorBrand = Color(0xFFDD0000)
    override val borderColorBrandLightOnly = Color(0xFFDD0000)
    override val borderColorBrandConst = Color(0xFFDD0000)
    override val borderColorNoContrast = Color(0xFFFFFFFF)
    override val iconColorIdle = Color(0xFF565A5F)
    override val iconColorDisabled = Color(0xFFA6ABB0)
    override val iconColorHover = Color(0xFF222628)
    override val iconColorActive = Color(0xFF222628)
    override val iconColorSecondaryOnLight = Color(0xFF565A5F)
    override val iconColorPrimaryOnDark = Color(0xFFFFFFFF)
    override val iconColorSecondaryOnDark = Color(0xFFDDE1E2)
    override val iconColorPrimaryOnLight = Color(0xFF222628)
    override val iconColorConstOnImage = Color(0xFFFFFFFF)
    override val iconColorSuccess = Color(0xFF006E3E)
    override val iconColorError = Color(0xFFC10000)
    override val iconColorWarning = Color(0xFF9E4401)
    override val iconColorBrand = Color(0xFFDD0000)
    override val iconColorBrandLightOnly = Color(0xFFDD0000)
    override val iconColorPrimary = Color(0xFF222628)
    override val iconColorSecondary = Color(0xFF565A5F)
    override val iconColorTertiary = Color(0xFF6E787C)
    override val iconColorPrimaryInverse = Color(0xFFDDE1E2)
    override val iconColorSecondaryInverse = Color(0xFFA6ABB0)
    override val iconColorInverseHighContrast = Color(0xFFFFFFFF)
}
