/**
 * Do not edit directly, this file was auto-generated.
 *
 * BILD Design System Tokens v1.0.0
 * Generated by Style Dictionary v5.1.4
 *
 * Context: Component: _dsysdoc
 * Aggregated component tokens with all modes
 *
 * Brand: Sportbild
 *
 * Copyright (c) 2026 Axel Springer Deutschland GmbH
 * Proprietary and confidential. All rights reserved.
 *
 * Documentation: https://github.com/UXWizard25/bild-design-system/blob/main/packages/tokens/docs/android.md
 */

package com.bild.designsystem.brands.sportbild.components._dsysdoc

import androidx.compose.runtime.Immutable
import androidx.compose.runtime.Composable
import com.bild.designsystem.shared.DesignSystemTheme
import androidx.compose.ui.graphics.Color

/**
 * _dsysdoc Design Tokens
 *
 * Usage:
 *   _dsysdocTokens.Colors.Light.primaryBgIdle
 *   _dsysdocTokens.Sizing.Compact.height
 *   _dsysdocTokens.Density.Default.contentGap
 */
object _dsysdocTokens {

    // ══════════════════════════════════════════════════════════════
    // COLORS
    // ══════════════════════════════════════════════════════════════
    object Colors {
        /**
         * Returns color tokens for the current theme.
         * Automatically resolves to Light or Dark based on DesignSystemTheme.isDarkTheme
         *
         * Usage:
         *   val bgColor = _dsysdocTokens.Colors.current().primaryBgIdle
         */
        @Composable
        fun current(): ColorTokens = if (DesignSystemTheme.isDarkTheme) Dark else Light

        /**
         * Interface for color tokens
         */
        interface ColorTokens {
            val dsDocSpacingItemBgColor: Color
            val dsDocSpacingItemBorderColor: Color
        }

        object Light : ColorTokens {
            override val dsDocSpacingItemBgColor = Color(0x1ADD0000)
            override val dsDocSpacingItemBorderColor = Color(0x80DD0000)
        }
        object Dark : ColorTokens {
            override val dsDocSpacingItemBgColor = Color(0x33FFFFFF)
            override val dsDocSpacingItemBorderColor = Color(0xCCFFFFFF)
        }
    }
}
