/**
 * Do not edit directly, this file was auto-generated.
 *
 * BILD Design System Tokens v1.0.0
 * Generated by Style Dictionary v5.1.4
 *
 * Context: Component: .DSDocsStyles
 * Aggregated component tokens with all modes
 *
 * Brand: Sportbild
 *
 * Copyright (c) 2026 Axel Springer Deutschland GmbH
 * Proprietary and confidential. All rights reserved.
 *
 * Documentation: https://github.com/UXWizard25/bild-design-system/blob/main/packages/tokens/docs/android.md
 */

package com.bild.designsystem.brands.sportbild.components..dsdocsstyles

import androidx.compose.runtime.Immutable

/**
 * .DSDocsStyles Design Tokens
 *
 * Usage:
 *   .DSDocsStylesTokens.Colors.Light.primaryBgIdle
 *   .DSDocsStylesTokens.Sizing.Compact.height
 *   .DSDocsStylesTokens.Density.Default.contentGap
 */
object .DSDocsStylesTokens {
}
