/**
 * Do not edit directly, this file was auto-generated.
 *
 * BILD Design System Tokens v1.0.0
 * Generated by Style Dictionary v5.1.4
 *
 * Context: Unified DesignColorScheme Interface (Dual-Axis Architecture)
 * All color brands implement this interface for polymorphic color access
 *
 * Copyright (c) 2026 Axel Springer Deutschland GmbH
 * Proprietary and confidential. All rights reserved.
 *
 * Documentation: https://github.com/UXWizard25/bild-design-system/blob/main/packages/tokens/docs/android.md
 */

package com.bild.designsystem.shared

import androidx.compose.runtime.Stable
import androidx.compose.ui.graphics.Color

/**
 * Unified color scheme interface for the BILD Design System
 *
 * All color brands (BILD, SportBILD) implement this interface,
 * enabling polymorphic color access across brands.
 *
 * This follows the Dual-Axis Architecture:
 * - ColorBrand axis: Determines which color palette (BILD or SportBILD)
 * - ContentBrand axis: Determines sizing/typography (BILD, SportBILD, or Advertorial)
 *
 * Usage:
 * ```kotlin
 * @Composable
 * fun MyComponent() {
 *     val colors: DesignColorScheme = DesignSystemTheme.colors
 *     Text(
 *         text = "Hello",
 *         color = colors.textColorPrimary
 *     )
 * }
 * ```
 */
@Stable
interface DesignColorScheme {
    val textColorPrimary: Color
    val textColorSecondary: Color
    val textColorMuted: Color
    val textColorAccent: Color
    val surfaceColorPrimary: Color
    val surfaceColorSecondary: Color
    val surfaceColorTertiary: Color
    val borderColorLowContrast: Color
    val borderColorMediumContrast: Color
    val borderColorHighContrast: Color
    val coreColorPrimary: Color
    val coreColorSecondary: Color
    val coreColorTertiary: Color
}
